var Ease;
(function (Ease) {
    Ease[Ease["LINEAR"] = 0] = "LINEAR";
    Ease[Ease["IN_SINE"] = 1] = "IN_SINE";
    Ease[Ease["OUT_SINE"] = 2] = "OUT_SINE";
    Ease[Ease["IN_OUT_SINE"] = 3] = "IN_OUT_SINE";
    Ease[Ease["IN_CUBIC"] = 4] = "IN_CUBIC";
    Ease[Ease["OUT_CUBIC"] = 5] = "OUT_CUBIC";
    Ease[Ease["IN_OUT_CUBIC"] = 6] = "IN_OUT_CUBIC";
    Ease[Ease["IN_QUINT"] = 7] = "IN_QUINT";
    Ease[Ease["OUT_QUINT"] = 8] = "OUT_QUINT";
    Ease[Ease["IN_OUT_QUINT"] = 9] = "IN_OUT_QUINT";
    Ease[Ease["IN_CIRC"] = 10] = "IN_CIRC";
    Ease[Ease["OUT_CIRC"] = 11] = "OUT_CIRC";
    Ease[Ease["IN_OUT_CIRC"] = 12] = "IN_OUT_CIRC";
    Ease[Ease["IN_ELASTIC"] = 13] = "IN_ELASTIC";
    Ease[Ease["OUT_ELASTIC"] = 14] = "OUT_ELASTIC";
    Ease[Ease["IN_OUT_ELASTIC"] = 15] = "IN_OUT_ELASTIC";
    Ease[Ease["IN_QUAD"] = 16] = "IN_QUAD";
    Ease[Ease["OUT_QUAD"] = 17] = "OUT_QUAD";
    Ease[Ease["IN_OUT_QUAD"] = 18] = "IN_OUT_QUAD";
    Ease[Ease["IN_QUART"] = 19] = "IN_QUART";
    Ease[Ease["OUT_QUART"] = 20] = "OUT_QUART";
    Ease[Ease["IN_OUT_QUART"] = 21] = "IN_OUT_QUART";
    Ease[Ease["IN_EXPO"] = 22] = "IN_EXPO";
    Ease[Ease["OUT_EXPO"] = 23] = "OUT_EXPO";
    Ease[Ease["IN_OUT_EXPO"] = 24] = "IN_OUT_EXPO";
    Ease[Ease["IN_BACK"] = 25] = "IN_BACK";
    Ease[Ease["OUT_BACK"] = 26] = "OUT_BACK";
    Ease[Ease["IN_OUT_BACK"] = 27] = "IN_OUT_BACK";
})(Ease || (Ease = {}));
export default Ease;
//# sourceMappingURL=Ease.js.map